const scheme = {
  // Stats
  s_td: '+# to Dexterity',
  s_ti: '+# to Intelligence',
  s_ts: '+# to Strength',
  s_tsai: '+# to Strength and Intelligence',
  s_tdai: '+# to Dexterity and Intelligence',
  s_tsad: '+# to Strength and Dexterity',
  s_is: '#% increased Strength',

  // Flat
  fl_tar: '+# to Accuracy Rating',
  fl_tmm: '+# to maximum Mana',
  fl_tmes: '+# to maximum Energy Shield',
  fl_tml: '+# to maximum Life',
  fl_ter: '+# to Evasion Rating',
  fl_ta: '+# to Armour',

  // Base
  b_iml: '#% increased maximum Life',
  b_imm: '#% increased maximum Mana',
  b_imrr: '#% increased Mana Regeneration Rate',
  b_olrps: '#% of Life Regenerated per second',
  b_oesrps: '#% of Energy Shield Regenerated per second',

  // Defence
  d_ier: '#% increased Evasion Rating',
  d_ia: '#% increased Armour',
  d_es: '#% increased maximum Energy Shield',
  d_ieraa: '#% increased Evasion Rating and Armour',
  d_ierwyho: '#% increased Evasion Rating while you have Onslaught',
  d_iesrr: '#% increased Energy Shield Recharge Rate',
  d_fsoesr: '#% faster start of Energy Shield Recharge',
  d_iawyhf: '#% increased Armour while you have Fortify',

  // Resistance
  r_tfr: '+#% to Fire Resistance',
  r_tcr: '+#% to Cold Resistance',
  r_tlr: '+#% to Lightning Resistance',
  r_taer: '+#% to all Elemental Resistances',
  r_tmcr: '+#% to maximum Cold Resistance',
  r_tmfr: '+#% to maximum Fire Resistance',
  r_tmlr: '+#% to maximum Lightning Resistance',
  r_tchr: '+#% to Chaos Resistance',
  r_erwhas: '+#% Elemental Resistances while holding a Shield',
  r_tcrdafe: '+#% to Chaos Resistance during any Flask Effect',
  r_yaaabyahtaer: 'You and Allies affected by your Auras have +#% to all Elemental Resistances',

  // Dodge
  do_actda: '#% additional chance to Dodge Attacks',
  do_ctda: '#% chance to Dodge Attacks',
  do_ctdsd: '#% Chance to Dodge Spell Damage',
  do_ctdalaleslctbsaa: '#% Chance to Dodge Attacks. #% less Armour, #% less Energy Shield, #% less Chance to Block Spells and Attacks',
  do_ctdsdwp: '#% chance to Dodge Spell Damage while Phasing',

  // Block
  bl_abc: '#% additional Block Chance',
  bl_tmbc: '+#% to maximum Block Chance',
  bl_obcats: '#% of Block Chance applied to Spells',
  bl_abcws: '#% additional Block Chance with Staves',

  // Shield
  sh_ipadwhas: '#% increased Physical Attack Damage while holding a Shield',
  sh_idfes: '#% increased Defences from Equipped Shield',
  sh_asdidwawhas: 'Attack Skills deal #% increased Damage with Ailments while holding a Shield',
  sh_actbws: '#% additional Chance to Block with Shields',
  sh_actbsws: '#% additional Chance to Block Spells with Shields',
  sh_iesfes: '#% increased Energy Shield from Equipped Shield',
  sh_iaswhas: '#% increased Attack Speed while holding a Shield',

  // Penetration
  pe_dwwper: 'Damage with Weapons Penetrates #% Elemental Resistance',
  pe_dwwpcr: 'Damage with Weapons Penetrates #% Cold Resistance',
  pe_dwwplr: 'Damage with Weapons Penetrates #% Lightning Resistance',
  pe_dwwpfr: 'Damage with Weapons Penetrates #% Fire Resistance',
  pe_dpoeer: 'Damage Penetrates #% of Enemy Elemental Resistances',
  pe_dper: 'Damage Penetrates #% Elemental Resistances',
  pe_dpfr: 'Damage Penetrates #% Fire Resistance',
  pe_dpcr: 'Damage Penetrates #% Cold Resistance',
  pe_dplr: 'Damage Penetrates #% Lightning Resistance',

  // Dot
  d_idot: '#% increased Damage over Time',
  d_idwb: '#% increased Damage with Bleeding',
  d_mdwb: '#% more Damage with Bleeding',
  d_idwp: '#% increased Damage with Poison',
  d_ipd: '#% increased Poison Duration',
  d_mdot: '#% more Damage over Time',
  d_pyiwcsdmd: 'Poison you inflict with Critical Strikes deals #% more Damage',
  d_ibd: '#% increased Bleeding Duration',

  // Crit
  cs_tcsm: '+#% to Critical Strike Multiplier',
  cs_icsc: '#% increased Critical Strike Chance',
  cs_tcsc: '+#% to Critical Strike Chance',
  cs_tcsmaetaofl: '+#% to Critical Strike Multiplier against Enemies that are on Full Life',
  cs_mcscaetaofl: '#% more Critical Strike Chance against Enemies that are on Full Life',
  cs_mcscaetaoll: '#% more Critical Strike Chance against Enemies that are on Low Life',

  // General Cast & Attack Speed
  ca_ics: '#% increased Cast Speed',
  ca_ias: '#% increased Attack Speed',
  ca_icswcs: '#% increased Cast Speed with Chaos Skills',
  ca_iaacs: '#% increased Attack and Cast Speed',
  ca_iaacswyhat: '#% increased Attack and Cast Speed while you have a Totem',
  ca_iaacsfeccr: '#% increased Attack and Cast Speed for each corpse consumed Recently',
  ca_iaacsiyuamsr: '#% increased Attack and Cast Speed if you\'ve used a Movement Skill Recently',

  // Spell
  sp_tsmfs: '+#% to Critical Strike Multiplier for Spells',
  sp_icscfs: '#% increased Critical Strike Chance for Spells',
  sp_MORE_msdwoll: '#% more Spell Damage when on Low Life',

  // General Melee
  me_imd: '#% increased Melee Damage',
  me_imas: '#% increased Melee Attack Speed',
  me_impd: '#% increased Melee Physical Damage',
  me_impdwyhf: '#% increased Melee Physical Damage while you have Fortify',
  me_idwafaswwamw: '#% increased Damage with Ailments from Attack Skills while wielding a Melee Weapon',
  me_imcsc: '#% increased Melee Critical Strike Chance',
  me_tmcsm: '+#% to Melee Critical Strike Multiplier',

  // General Projectile
  p_sct: 'Skills Chain +# times',
  p_iad: '#% increased Projectile Damage',
  p_ips: '#% increased Projectile Speed',
  p_ppat: 'Projectiles Pierce # additional Targets',
  p_phicscattp: 'Projectiles have #% increased Critical Strike Chance against Targets they Pierce',

  // General Damage
  g_iad: '#% increased Attack Damage',
  g_icd: '#% increased Chaos Damage',
  g_igpd: '#% increased Global Physical Damage',
  g_isd: '#% increased Spell Damage',
  g_ipapd: '#% increased Attack Physical Damage',
  g_ied: '#% increased Elemental Damage',
  g_opdctcd: '#% of Physical Damage Converted to Cold Damage',
  g_iedwas: '#% increased Elemental Damage with Attack Skills',
  g_ildwas: '#% increased Lightning Damage with Attack Skills',
  g_icdwas: '#% increased Cold Damage with Attack Skills',
  g_ieddafe: '#% increased Elemental Damage during any Flask Effect',
  g_iedwas: '#% increased Elemental Damage with Attack Skills',
  g_idiyhcacr: '#% increased Damage if you have consumed a corpse Recently',
  g_yaadidwabayc: 'You and Allies deal #% increased Damage while affected by Auras you Cast',
  g_idwhaetaoll: '#% increased Damage with Hits against Enemies that are on Low Life',
  g_idwl: '#% increased Damage while Leeching',

  // Cold
  c_icd: '#% increased Cold Damage',
  c_icdwas: '#% increased Cold Damage with Attack Skills',
  c_fyhasbal: 'Chills from your Hits always Slow by at least #%',
  c_ctfewac: '#% chance to Freeze Enemies which are Chilled',

  // Lightning
  l_sfyhaidtbal: 'Shocks from your Hits always increase Damage taken by at least #%',
  l_ild: '#% increased Lightning Damage',
  l_ieos: '#% increased Effect of Shock',
  l_sfyhaidtbal: 'Shocks from your Hits always increase Damage taken by at least #%',

  // Fire
  f_ifd: '#% increased Fire Damage',
  f_icswfs: '#% increased Cast Speed with Fire Skills',
  f_ifdwas: '#% increased Fire Damage with Attack Skills',

  // Burning
  bu_ibd: '#% increased Burning Damage',

  // Mine
  m_imd: '#% increased Mine Damage',
  m_imls: '#% increased Mine Laying Speed',
  m_imdu: '#% increased Mine Duration',
  m_tcsmwm: '+#% to Critical Strike Multiplier with Mines',
  m_icscwm: '#% increased Critical Strike Chance with Mines',
  m_chutarmpaat: 'Can have up to # additional Remote Mine placed at a time',
  m_chutarmpaat1: 'Can have up to # additional Remote Mines placed at a time',
  m_imas: '#% increased Mine Arming Speed',
  m_pen: 'Mine Damage Penetrates #% Elemental Resistances',
  m_imdaoe: '#% increased Mine Detonation Area of Effect',

  // Trap
  t_itts: '#% increased Trap Throwing Speed',
  t_itd: '#% increased Trap Damage',
  t_icrsftt: '#% increased Cooldown Recovery Speed for throwing Traps',
  t_iaoeft: '#% increased Area of Effect for Traps',
  t_tcsmwt: '+#% to Critical Strike Multiplier with Traps',
  t_icscwt: '#% increased Critical Strike Chance with Traps',
  t_ittaoe: '#% increased Trap Trigger Area of Effect',
  t_chutatpaat: 'Can have up to # additional Trap placed at a time',
  t_chutatpaat1: 'Can have up to # additional Traps placed at a time',
  t_ctgafcwytitbne: '#% chance to gain a Frenzy Charge when your Trap is triggered by an Enemy',
  t_pen: 'Trap Damage Penetrates #% Elemental Resistances',

  // Dagger
  da_cswdhactpte: 'Critical Strikes with Daggers have a #% chance to Poison the Enemy',
  da_tcsmwd: '+#% to Critical Strike Multiplier with Daggers',
  da_icscwd: '#% increased Critical Strike Chance with Daggers',
  da_ipdwd: '#% increased Physical Damage with Daggers',
  da_idwafaswwad: '#% increased Damage with Ailments from Attack Skills while wielding a Dagger',
  da_iaswd: '#% increased Attack Speed with Daggers',
  da_iarwd: '#% increased Accuracy Rating with Daggers',

  // Axe
  ax_idwafaswwaa: '#% increased Damage with Ailments from Attack Skills while wielding an Axe',
  ax_ipdwa: '#% increased Physical Damage with Axes',
  ax_iaswa: '#% increased Attack Speed with Axes',
  ax_iarwa: '#% increased Accuracy Rating with Axes',

  // Claws
  cl_iaswc: '#% increased Attack Speed with Claws',
  cl_idwafaswwac: '#% increased Damage with Ailments from Attack Skills while wielding a Claw',
  cl_ipdwc: '#% increased Physical Damage with Claws',
  cl_icscwc: '#% increased Critical Strike Chance with Claws',
  cl_tcsmwc: '+#% to Critical Strike Multiplier with Claws',
  cl_iarwc: '#% increased Accuracy Rating with Claws',

  // Mace
  ma_idwafaswwam: '#% increased Damage with Ailments from Attack Skills while wielding a Mace',
  ma_ipdwm: '#% increased Physical Damage with Maces',
  ma_restwm: '#% reduced Enemy Stun Threshold with Maces',
  ma_iaswm: '#% increased Attack Speed with Maces',
  ma_icscwm: '#% increased Critical Strike Chance with Maces',
  ma_tcsmwm: '+#% to Critical Strike Multiplier with Maces',
  ma_uarwm: '#% increased Accuracy Rating with Maces',
  ma_iedwm: '#% increased Elemental Damage with Maces',

  // Staves
  st_iarws: '#% increased Accuracy Rating with Staves',
  st_iasws: '#% increased Attack Speed with Staves',
  st_idwafaswwas: '#% increased Damage with Ailments from Attack Skills while wielding a Staff',
  st_igcscwwas: '#% increased Global Critical Strike Chance while wielding a Staff',
  st_tgcsmwwas: '+#% to Global Critical Strike Multiplier while wielding a Staff',
  st_ipdws: '#% increased Physical Damage with Staves',
  st_igcsscwwas: '#% increased Global Critical Strike Chance while wielding a Staff',
  st_icscws: '#% increased Critical Strike Chance with Staves',

  // Swords
  sw_ipdws: '#% increased Physical Damage with Swords',
  sw_iasws: '#% increased Attack Speed with Swords',
  sw_tarws: '+# to Accuracy Rating with Swords',
  sw_idwafaswwas: '#% increased Damage with Ailments from Attack Skills while wielding a Sword',
  sw_icscws: '#% increased Critical Strike Chance with Swords',
  sw_tcsmws: '+#% to Critical Strike Multiplier with Swords',
  sw_iarws: '#% increased Accuracy Rating with Swords',

  // Wand
  w_ipdww: '#% increased Physical Damage with Wands',
  w_idww: '#% increased Damage with Wands',
  w_idwafaswwaw: '#% increased Damage with Ailments from Attack Skills while wielding a Wand',
  w_gowpdaefd: 'Gain #% of Wand Physical Damage as Extra Fire Damage',
  w_gowpdaecd: 'Gain #% of Wand Physical Damage as Extra Cold Damage',
  w_gowpdaeld: 'Gain #% of Wand Physical Damage as Extra Lightning Damage',
  w_gopdaecd: 'Gain #% of Physical Damage as Extra Chaos Damage',
  w_iasww: '#% increased Attack Speed with Wands',
  w_iarww: '#% increased Accuracy Rating with Wands',
  w_tcsmww: '+#% to Critical Strike Multiplier with Wands',
  w_icscww: '#% increased Critical Strike Chance with Wands',
  w_iwdppc: '#% increased Wand Damage per Power Charge',
  w_iedww: '#% increased Elemental Damage with Wands',

  // Bow
  bo_iarwb: '#% increased Accuracy Rating with Bows',
  bo_idwb: '#% increased Damage with Bows',
  bo_icscwb: '#% increased Critical Strike Chance with Bows',
  bo_ipdwb: '#% increased Physical Damage with Bows',
  bo_tcsmwb: '+#% to Critical Strike Multiplier with Bows',
  bo_idwafaswwab: '#% increased Damage with Ailments from Attack Skills while wielding a Bow',
  bo_iaswb: '#% increased Attack Speed with Bows',
  bo_ias: '#% increased Arrow Speed',
  bo_bhctcb: 'Bow Attacks have #% chance to cause Bleeding',
  bo_koth: 'Knocks Back Enemies if you get a Critical Strike with a Bow',
  bo_restwb: '#% reduced Enemy Stun Threshold with Bows',
  bo_isdwboe: '#% increased Stun Duration with Bows on Enemies',

  // Dual Wielding
  dw_iarwdw: '#% increased Accuracy Rating while Dual Wielding',
  dw_ipwdwdw: '#% increased Physical Weapon Damage while Dual Wielding',
  dw_asdidwawdw: 'Attack Skills deal #% increased Damage with Ailments while Dual Wielding',
  dw_abcwdw: '#% additional Block Chance while Dual Wielding',
  dw_iaswdw: '#% increased Attack Speed while Dual Wielding',
  dw_icswdw: '#% increased Cast Speed while Dual Wielding',
  dw_abcwdwohas: '#% additional Block Chance while Dual Wielding or holding a Shield',
  dw_iwcscwdw: '#% increased Weapon Critical Strike Chance while Dual Wielding',
  dw_iadwmh: '#% increased Attack Damage with Main Hand',
  dw_iaswoh: '#% increased Attack Speed with Off Hand',

  // One Handed
  oh_iarwohmw: '#% increased Accuracy Rating with One Handed Melee Weapons',
  oh_iaswohmw: '#% increased Attack Speed with One Handed Melee Weapons',
  oh_ipdwohmw: '#% increased Physical Damage with One Handed Melee Weapons',
  oh_iaswohmw: '#% increased Attack Speed with One Handed Melee Weapons',
  oh_icscwohmw: '#% increased Critical Strike Chance with One Handed Melee Weapons',
  oh_idwafaswwaohw: '#% increased Damage with Ailments from Attack Skills while wielding a One Handed Weapon',
  oh_iaswohw: '#% increased Attack Speed with One Handed Weapons',
  oh_idwohw: '#% increased Damage with One Handed Weapons',

  // Two Handed Weapons
  th_idwthw: '#% increased Damage with Two Handed Weapons',
  th_iaswthmw: '#% increased Attack Speed with Two Handed Melee Weapons',
  th_idwafaswwathw: '#% increased Damage with Ailments from Attack Skills while wielding a Two Handed Weapon',
  th_ipdwthmw: '#% increased Physical Damage with Two Handed Melee Weapons',
  th_iarwthmw: '#% increased Accuracy Rating with Two Handed Melee Weapons',
  th_isdwthmwoe: '#% increased Stun Duration with Two Handed Melee Weapons on Enemies',

  // Totem
  to_itd: '#% increased Totem Damage',
  to_itps: '#% increased Totem Placement speed',
  to_enytdls: 'Enemies near your Totems deal #% less Damage',
  to_enyttipafd: 'Enemies near your Totems take #% increased Physical and Fire Damage',
  to_chutatsaat: 'Can have up to # additional Totem summoned at a time',
  to_itdu: '#% increased Totem Duration',
  to_tcsmwts: '+#% to Critical Strike Multiplier with Totem Skills',
  to_scbthics: 'Spells Cast by Totems have #% increased Cast Speed',
  to_aubthias: 'Attacks used by Totems have #% increased Attack Speed',
  to_itl: '#% increased Totem Life',
  to_tgtaer: 'Totems gain +#% to all Elemental Resistances',
  to_thapdr: 'Totems have #% additional Physical Damage Reduction',
  to_icscwts: '#% increased Critical Strike Chance with Totem Skills',

  // Curse
  cu_echac: 'Enemies can have # additional Curse',
  cu_reocoy: '#% reduced Effect of Curses on You',
  cu_ieoyc: '#% increased Effect of your Curses',
  cu_iaoeocs: '#% increased Area of Effect of Curse Skills',
  cu_icd: '#% increased Curse Duration',
  cu_icsfc: '#% increased Cast Speed for Curse',
  cu_icsfc: '#% increased Cast Speed for Curses',

  // Stun
  stu_isdoe: '#% increased Stun Duration on Enemies',
  stu_ibr: '#% increased Block Recovery',
  stu_ctabs: '#% chance to Avoid being Stunned',
  stu_isabr: '#% increased Stun and Block Recovery',
  stu_isdoepec: '#% increased Stun Duration on Enemies per Endurance Charge',
  stu_ist: '#% increased Stun Threshold',
  stu_rest: '#% reduced Enemy Stun Threshold',

  // Aliment
  al_ctf: '#% chance to Freeze',
  al_cti: '#% chance to Ignite',
  al_ctfsai: '#% chance to Freeze, Shock and Ignite',
  al_ahctcb: 'Attacks have #% chance to cause Bleeding',
  al_ctpoh: '#% chance to Poison on Hit',
  al_ctpohwa: '#% chance to Poison on Hit with Attacks',
  al_ieonaoe: '#% increased Effect of non-Damaging Ailments on Enemies',
  al_idoeaoe: '#% increased Duration of Elemental Ailments on Enemies',
  al_ieoc: '#% increased Effect of Chill',
  al_icdoe: '#% increased Chill Duration on Enemies',
  al_ifdoe: '#% increased Freeze Duration on Enemies',
  al_cts: '#% chance to Shock',
  al_isdoe: '#% increased Shock Duration on Enemie',
  al_isdoe: '#% increased Shock Duration on Enemies',
  al_iidoe: '#% increased Ignite Duration on Enemies',

  // Leech
  le_illps: '#% increased Life Leeched per second',
  le_opadlal: '#% of Physical Attack Damage Leeched as Life',
  le_oadlam: '#% of Attack Damage Leeched as Mana',
  le_oadlal: '#% of Attack Damage Leeched as Life',
  le_imlps: '#% increased Mana Leeched per second',
  le_ommpstmmlr: '+#% of maximum Mana per second to maximum Mana Leech rate',
  le_mgfeehbya: '+# Mana gained for each Enemy hit by your Attacks',
  le_lgfeehbya: '+# Life gained for each Enemy hit by your Attacks',
  le_osdlalwyhas: '#% of Spell Damage Leeched as Life while you have Arcane Surge',
  le_omlpstmllr: '+#% of maximum Life per second to maximum Life Leech rate',
  le_oddbytiltyal: '#% of Damage dealt by your Totems is Leeched to you as Life',
  le_poc: '#% of Elemental Damage Leeched as Life',
  le_oadlalamiykr: '#% of Attack Damage Leeched as Life and Mana if you\'ve Killed Recently',

  // Minions
  mi_mdid: 'Minions deal #% increased Damage',
  mi_csutagaat: 'Can Summon up to # additional Golem at a time',
  mi_mhctb: 'Minions have #% Chance to Block',
  mi_mrotmlwtb: 'Minions Recover #% of their Maximum Life when they Block',
  mi_mrlps: 'Minions Regenerate #% Life per second',
  mi_mhtaer: 'Minions have +#% to all Elemental Resistances',
  mi_tmnoz: '+# to Maximum number of Zombies',
  mi_mhiml: 'Minions have #% increased maximum Life',
  mi_shiml: 'Spectres have #% increased maximum Life',
  mi_shid: 'Spectres have #% increased Damage',
  mi_imdiyuamsr: '#% increased Minion Damage if you\'ve used a Minion Skill Recently',
  mi_mhiaacsiyoynhjr: 'Minions have #% increased Attack and Cast Speed if you or your Minions have Killed Recently',
  mi_mhims: 'Minions have #% increased Movement Speed',
  mi_isms: '#% increased Skeleton Movement Speed',
  mi_imd: '#% increased Minion Duration',
  mi_rzsahiaoe: 'Raised Zombies\' Slam Attack has #% increased Area of Effect',
  mi_rzsahicrs: 'Raised Zombies\' Slam Attack has #% increased Cooldown Recovery Speed',
  mi_yrzsccoddotmlacdps: 'Your Raised Zombies spread Caustic Cloud on Death, dealing #% of their maximum Life as Chaos Damage per second',
  mi_yaymhapdrfezyo: 'You and your Minions have #% additional Physical Damage Reduction for each Zombie you own',
  mi_mhias: 'Minions have #% increased Attack Speed',
  mi_mhics: 'Minions have #% increased Cast Speed',
  mi_mlodal: 'Minions Leech #% of Damage as Life',
  mi_tmnos: '+# to Maximum number of Spectres',
  mi_saswwss: 'Summon # additional Skeleton Warriors with Summon Skeleton',
  mi_sdid: 'Skeletons deal #% increased Damage',
  mi_tmnosk: '+# to Maximum number of Skeletons',
  mi_mhtcr: 'Minions have +#% to Chaos Resistance',

  // Flasks
  fl_rfcu: '#% reduced Flask Charges used',
  fl_ieofoy: '#% increased effect of Flasks on You',
  fl_ifed: '#% increased Flask effect duration',
  fl_imrff: '#% increased Mana Recovery from Flasks',
  fl_ifcg: '#% increased Flask Charges gained',
  fl_ilrff: '#% increased Life Recovery from Flasks',
  fl_imsdafe: '#% increased Movement Speed during any Flask Effect',
  fl_iasdafe: '#% increased Attack Speed during any Flask Effect',
  fl_fgces: 'Flasks gain # Charges every # seconds',
  fl_cfyftncc: '#% chance for your Flasks to not consume Charges',
  fl_ctpohdafe: '#% chance to Poison on Hit during any Flask Effect',
  fl_ctfsaidafe: '#% chance to Freeze, Shock and Ignite during any Flask Effect',
  fl_ifrr: '#% increased Flask Recovery rate',

  // Aura
  a_lmr: '#% less Mana Reserved',
  a_rmr: '#% reduced Mana Reserved',
  a_ieonayc: '#% increased effect of Non-Curse Auras you Cast',
  a_iaof: '#% increased Area of Effect',
  a_ieohoy: '#% increased Effect of Heralds on You',
  a_lmros: '#% less Mana Reservation of Skills',
  a_aycgiaacstyaa: 'Auras you Cast grant #% increased Attack and Cast Speed to you and Allies',

  // AoE
  aoe_iaoe: '#% increased Area of Effect',
  aoe_iad: '#% increased Area Damage',
  aoe_iaoewyhas: '#% increased Area of Effect while you have Arcane Surge',

  // duration
  du_ised: '#% increased Skill Effect Duration',
  du_iaoeoas: '#% increased Area of Effect of Aura Skills',

  // charges
  ch_tmfc: '+# to Maximum Frenzy Charges',
  ch_tmpc: '+# to Maximum Power Charges',
  ch_tmec: '+# to Maximum Endurance Charges',
  ch_tmfcampc: '+# to Maximum Frenzy Charges and Maximum Power Charges',
  ch_ierpfc: '#% increased Evasion Rating per Frenzy Charge',
  ch_ifcd: '#% increased Frenzy Charge Duration',
  ch_iaoeppc: '#% increased Area of Effect per Power Charge',
  ch_isdppc: '#% increased Spell Damage per Power Charge',
  ch_iecd: '#% increased Endurance Charge Duration',
  ch_ipcd: '#% increased Power Charge Duration',
  ch_idpfc: '#% increased Damage per Frenzy Charge',
  ch_idppc: '#% increased Damage per Power Charge',
  ch_dperwyhapc: 'Damage Penetrates #% Elemental Resistances while you have a Power Charge',
  ch_iefapcd: '#% increased Endurance, Frenzy and Power Charge Duration',
  ch_ctgapcocs: '#% chance to gain a Power Charge on Critical Strike',
  ch_idpec: '#% increased Damage per Endurance Charge',
  ch_tcsmppc: '+#% to Critical Strike Multiplier per Power Charge',
  ch_cscwampc: '+#% Critical Strike Chance while at maximum Power Charges',
  ch_iaoepec: '#% increased Area of Effect per Endurance Charge',
  ch_apdrpec: '#% additional Physical Damage Reduction per Endurance Charge',
  ch_redtwamec: '#% reduced Elemental Damage taken while at Maximum Endurance Charges',
  ch_tcrpec: '+#% to Chaos Resistance per Endurance Charge',
  ch_iadpfc: '#% increased Attack Damage per Frenzy Charge',
  ch_iaspfc: '#% increased Attack Speed per Frenzy Charge',
  ch_imspfc: '#% increased Movement Speed per Frenzy Charge',
  ch_ctgafcaapcok: '#% chance to gain a Frenzy Charge and a Power Charge on Kill',
  ch_ctgapfoecoh: '#% chance to gain a Power, Frenzy or Endurance Charge on Hit',
  ch_ctgaecwygapc: '#% chance to gain an Endurance Charge when you gain a Power Charge',
  ch_ctgapcwypat: '#% chance to gain a Power Charge when you place a Totem',
  ch_ctgapciyoytkae: '#% chance to gain a Power Charge if you or your Totems kill an Enemy',

  // Misc
  o_iod: '#% increased Onslaught duration',
  o_iar: '#% increased Accuracy Rating',
  o_ims: '#% increased Movement Speed',
  o_ioe: '#% increased Onslaught Effect',
  o_imswp: '#% increased Movement Speed while Phasing',
  o_imswyhes: '#% increased Movement Speed while you have Energy Shield',
  o_ctdaasdwyhes: '#% chance to Dodge Attacks and Spell Damage while you have Energy Shield',
  o_mctewofes: '#% more chance to Evade while on full Energy Shield',
  o_iaacsiesrhsr: '#% increased Attack and Cast Speed if Energy\nShield Recharge has started Recently',
  o_ctbwhabe: '#% chance to Blind with Hits against Bleeding Enemies',
  o_idwhaaabe: '#% increased Damage with Hits and Ailments against Blinded Enemies',
  o_rredt: '#% reduced Reflected Elemental Damage taken',
  o_ctgofsok: '#% chance to gain Onslaught for # seconds on Kill',
  o_rmcos: '#% reduced Mana Cost of Skills',
  o_tcbdfsabt: 'Traps cannot be Damaged for # seconds after being Thrown',
  o_mcbdfsabp: 'Mines cannot be Damaged for # seconds after being Placed',
  o_ctspfaecohwc: '#% chance to Steal Power, Frenzy, and Endurance Charges on Hit with Claws',
  o_ctaifswc: '#% chance to Avoid interruption from Stuns while Casting',
  o_tmwaur: '+# to Melee Weapon and Unarmed range',
  o_gofswykarue: 'Gain Onslaught for # seconds when you Kill a Rare or Unique Enemy',
  o_iwcrs: '#% increased Warcry Cooldown Recovery Speed',
  o_iwd: '#% increased Warcry Duration',
  o_ctgrwyharue: '#% chance to gain # Rage when you Hit a Rare or Unique Enemy',
  o_ctgapcwytitbae: '#% chance to gain a Power Charge when your Trap is triggered by an Enemy',
  o_ctgapcwymidtae: '#% chance to gain a Power Charge when your Mine is Detonated targeting an Enemy',
  o_idt: '#% increased Damage taken',
  o_thoya: 'Totems have #% of your Armour',
  o_subthacttoh: 'Skills used by Totems have a #% chance to Taunt on Hit',
  o_yrompspt: 'You Regenerate #% of Mana per second per Totem',
  o_yaytrolpspt: 'You and your Totems Regenerate #% of Life per second per Totem',
  o_oditfmbl: '#% of Damage is taken from Mana before Life',
  o_redt: '#% reduced Elemental Damage taken',
  o_redtwyhaec: '#% reduced Elemental Damage taken while you have an Endurance Charge',
  o_isdwyhas: '#% increased Spell Damage while you have Arcane Surge',
  o_idpekbyoytr: '#% increased Damage per Enemy Killed by you or your Totems Recently',
  o_rmcoswofes: '#% reduced Mana Cost of Skills while on Full Energy Shield',
  o_gommaemes: 'Gain #% of Maximum Mana as Extra Maximum Energy Shield',
  o_igcsciysatr: '#% increased Global Critical Strike Chance if you\'ve Summoned a Totem Recently',
  o_ctgapforcok: '#% chance to gain a Power, Frenzy or Endurance Charge on Kill',
  o_yanahiacamiywr: 'You and nearby allies have #% increased Attack, Cast and Movement Speed if you\'ve Warcried Recently',
  o_omlrpspec: '#% of maximum Life Regenerated per second per Endurance Charge',
  o_idwhafsoie: '#% increased Damage with Hits against Frozen, Shocked or Ignited Enemies',
  o_ctgafcwyharoue: '#% chance to gain a Frenzy Charge when you Hit a Rare or Unique Enemy',
  o_ctaea: '#% chance to Avoid Elemental Ailments',
  o_ctgapcwyb: '#% chance to gain a Power Charge when you Block',
  o_ctgaecomcs: '#% chance to gain an Endurance Charge on Melee Critical Strike',
  o_lgok: '+# Life gained on Kill',
  o_glwuhabe: 'Gain +# Life when you Hit a Bleeding Enemy',
  o_gicscabe: '#% increased Critical Strike Chance against Bleeding Enemies',
  o_tcsmabe: '+#% to Critical Strike Multiplier against Bleeding Enemies',
  o_imsiykr: '#% increased Movement Speed if you\'ve Killed Recently',
  o_mgok: '+# Mana gained on Kill',
  o_yohreoy: 'Your Offerings have #% reduced Effect on You',
  o_mtcsmaatdmfafcsaotvldwh: 'Modifiers to Critical Strike Multiplier also apply to Damage Multiplier for Ailments from Critical Strikes at #% of their value\n#% less Damage with Hits',
  o_odtgamoswh: '#% of Damage taken gained as Mana over # seconds when Hit',
  o_eyhwedtgrtteartoe: 'Enemies you hit with Elemental Damage temporarily get +#% Resistance to those Elements and -#% Resistance to other Elements',
  o_lrpsfeoyttrut: '#% Life Regenerated per Second for each of your Traps Triggered Recently, up to #%',
  o_lrpsfeoymdrut: '#% Life Regenerated per Second for each of your Mines Detonated Recently, up to #%',
  o_ctbeoh: '#% chance to Blind Enemies on Hit',
  o_ctccgwyharouels: '#% chance to create Consecrated Ground when you Hit a Rare or Unique Enemy, lasting # seconds',
  o_ctccgwhls: '#% chance to create Consecrated Ground when Hit, lasting # seconds',
  o_ctccgokls: '#% chance to create Consecrated Ground on Kill, lasting # seconds',
  o_cgycgidtyaa: 'Consecrated Ground you create grants #% increased Damage to you and Allies',
  o_esomlroos: 'Every # seconds, #% of Maximum Life Regenerated over one second',
  o_aycgpdrtyal: 'Auras you Cast grant +#% Physical Damage Reduction to you and Allies',
  o_aycgomlrpstyaa: 'Auras you Cast grant #% of Maximum Life Regenerated per second to\nyou and Allies',
  o_ibaamacrs: '#% increased Blink Arrow and Mirror Arrow Cooldown Recovery Speed',
  o_ieotoyfesyurut: '#% increased Effect of Tailwind on You for each Skill you\'ve used Recently, up to #%',
  o_erwyht: '+# Evasion Rating while you have Tailwind',
  o_ilr: '#% increased Light Radius',
  o_pdmdferc: 'Projectiles deal #% more Damage for each remaining Chain',
  o_gopdaedoare: 'Gain #% of Physical Damage as Extra Damage of a random Element',
  o_eyktaabeagifc: 'Enemies you Kill that are affected by Elemental Ailments\ngrant #% increased Flask Charges',
  o_icscaetaabnea: '#% increased Critical Strike Chance against Enemies that are affected\nby no Elemental Ailments',
  o_tcsmaetaabea: '+#% to Critical Strike Multiplier against Enemies that are affected\nby Elemental Ailments',
  o_iccrs: '#% increased Convocation Cooldown Recovery Speed',
  o_cfatmohape: '#% chance for Attacks to Maim on Hit against Poisoned Enemies',
  o_ipdppar: '#% increased Poison Duration per Poison applied Recently',
  o_idwtioone: '#% increased Damage while there is only one nearby Enemy',
  o_ctgapconcs: '#% chance to gain a Power Charge on non-Critical Strike',
  o_rdtfdovt: '#% reduced Damage taken from Damage Over Time',
  o_gopdaecdape: 'Gain #% of Physical Damage as Extra Chaos Damage against\nPoisoned Enemies',
  o_roymlppaeyk: 'Recover #% of your maximum Life per Poison affecting Enemies you Kill',
  o_pgdattfdutidwhtt: 'Projectiles gain Damage as they travel further, dealing up\nto #% increased Damage with Hits to targets',
  o_mediycitpsncsmndmfafcs: '#% more Elemental Damage if you\'ve Crit in the past # seconds\nNo Critical Strike Multiplier\nNo Damage Multiplier for Ailments from Critical Strikes',
  o_ceeacbs: 'Cannot Evade enemy Attacks\nCannot be Stunned',
  o_abcfehybitps: '#% additional Block Chance for each Hit you\'ve Blocked in the past # seconds',
  o_ipdiybahfaueitps: '#% increased Physical Damage if you\'ve Blocked a Hit from a Unique Enemy in the past # seconds',
  o_ipdfehybitps: '#% increased Physical Damage for each Hit you\'ve Blocked in the past # seconds',
  o_idiytndfhr: '#% increased Damage if you\'ve taken no Damage from Hits Recently',
  o_abciywdbahr: '#% additional Block Chance if you were Damaged by a Hit Recently',
  o_embytipd: 'Enemies Maimed by you take #% increased Physical Damage',
  o_rpdtwamec: '#% reduced Physical Damage taken while at maximum Endurance Charges',
  o_mpdwamfc: '#% more Physical Damage while at maximum Frenzy Charges',
  o_ctgaecokwoh: '#% chance to gain an Endurance Charge on Kill with Off Hand',
  o_ctgafcok: '#% chance to gain a Frenzy Charge on Kill',
  o_ctgafcokwmh: '#% chance to gain a Frenzy Charge on Kill with Main Hand',
  o_beykedotmlapd: 'Bleeding Enemies you Kill Explode, dealing #% of\ntheir Maximum Life as Physical Damage',
  o_idwhaaablee: '#% increased Damage with Hits and Ailments against Bleeding Enemies',
  o_rdt: '#% reduced Damage taken',
  o_otpdpfhitpsiralps: '#% of Total Physical Damage prevented from Hits in the past # seconds is Regenerated as Life per second',
  o_ctgaecwysae: '#% chance to gain an Endurance Charge when you Stun an Enemy',
  o_iaspar: '#% increased Attack Speed per # Accuracy Rating',
  o_iariydacsitps: '#% increased Accuracy Rating if you\'ve dealt a Critical Strike in the past # seconds',
  o_idiydacsitps: '#% increased Damage if you\'ve dealt a Critical Strike in the past # seconds',
  o_iaddo: '#% increased Attack Damage during Onslaught',
  o_gpfsok: 'Gain Phasing for # seconds on Kill',
  o_ctgaecwyah: '#% chance to gain an Endurance Charge when you are Hit',
  o_gofsok: 'Gain Onslaught for # seconds on Kill',
  o_ctgofswyharoue: '#% chance to gain Onslaught for # Seconds when you Hit a Rare\nor Unique Enemy',
  o_mctepado: '#% more chance to Evade Projectile Attacks during Onslaught',
  o_mctemado: '#% more chance to Evade Melee Attacks during Onslaught',
  o_iadabe: '#% increased Attack Damage against Bleeding Enemies',
  o_ikd: '#% increased Knockback Distance',
  o_ctkeboh: '#% chance to Knock Enemies Back on hit',
  o_netied: 'Nearby Enemies Take #% increased Elemental Damage',
  o_ctfomh: '#% chance to Fortify on Melee hit',
  o_eyttid: 'Enemies you Taunt take #% increased Damage',
  o_cttoh: '#% chance to Taunt on Hit',
  o_yanahims: 'You and nearby Allies have #% increased Movement Speed',
  o_rpdt: '#% reduced Reflected Physical Damage taken',
  o_ytredfcs: 'You take #% reduced Extra Damage from Critical Strikes',
  o_rdtfbe: '#% reduced Damage taken from Blinded Enemies',
  o_ctabi: '#% chance to Avoid being Ignited',
  o_ctabf: '#% chance to Avoid being Frozen',
  o_ctabs: '#% chance to Avoid being Shocked',
  o_ctabc: '#% chance to Avoid being Chilled',
  o_rmcostpmott: '#% reduced Mana Cost of Skills that place Mines or throw Traps',
  o_ieofoy: '#% increased effect of Fortify on You',
  o_ifd: '#% increased Fortify duration',
  o_apdr: '#% additional Physical Damage Reduction',
  o_opdctfd: '#% of Physical Damage Converted to Fire Damage',
  o_pfd: '#% of Physical Damage from Hits taken as Fire Damage',
  o_itd: '#% increased Taunt Duration',
  o_rdtiytaer: '#% reduced Damage taken if you\'ve Taunted an Enemy Recently',
  o_olrpsiytaer: '#% of Life Regenerated per second if you\'ve Taunted an Enemy Recently',
  o_etbydldwhaaaot: 'Enemies Taunted by you deal #% less Damage with Hits and Ailments against other targets',
  o_mgwyb: '+# Mana gained when you Block',

  // Misc no values
  ov_ctred: 'Cannot take Reflected Elemental Damage',
  ov_titpdfsatpaawama: 'The increase to Physical Damage from Strength applies to Projectile Attacks as well as Melee Attacks',
  ov_sefapcwnpm: 'Share Endurance, Frenzy and Power Charges with nearby party members',
  ov_gaecesiybhr: 'Gain an Endurance Charge every seconfd if you\'ve been Hit Recently',
  ov_cbc: 'Cannot be Chilled',
  ov_cbs: 'Cannot be Stunned',
  ov_gaecesiybhr: 'Gain an Endurance Charge every second if you\'ve been Hit Recently',
  ov_dfycscbr: 'Damage from your Critical Strikes cannot be Reflected',
  ov_yosaay: 'Your Offering Skills also affect you',
  ov_yanpmspfaecweo: 'You and Nearby Party Members Share Power, Frenzy and Endurance Charges with each other',
  ov_mwbdcytted: 'Moving while Bleeding doesn\'t cause you to take extra Damage',
  ov_fs: 'Far Shot',
  ov_ppant: 'Projectiles Pierce all nearby Targets',
  ov_sfaap: 'Skills fire an additional Projectile',
  ov_iyuasryanaht: 'If you\'ve used a Skill Recently, You and nearby Allies have Tailwind',
  ov_sshcbe: 'Summoned Skeletons\' hits can\'t be Evaded',
  ov_rbwyuaf: 'Removes Bleeding when you use a Flask',
  ov_gafcwydacs: 'Gain a Flask Charge when you deal a Critical Strike',
  ov_iteadafe: 'Immune to Elemental Ailments during any Flask Effect',
  ov_ytnedfcswtioone: 'You take no Extra Damage from Critical Strikes while there is only one nearby Enemy',
  ov_dmii: 'Detonating Mines is Instant',
  ov_cshcs: 'Critical Strikes have Culling Strike',
  ov_iampfa: 'Ignore all Movement Penalties from Armour',
  ov_ppadt: 'Projectiles Pierce an additional Target',
  ov_cbsbhyb: 'Cannot be Stunned by Hits you Block',
  ov_ycddd: 'Your Counterattacks deal Double Damage',
  ov_amohabe: 'Attacks Maim on Hit against Bleeding Enemies',
  ov_yhcbendcs: 'Your hits can\'t be Evaded\nNever deal Critical Strikes',
  ov_arfbaid: 'Armour received from Body Armour is doubled',
  ov_mscbmtbbv: 'Movement Speed cannot be modified to below base value',
  ov_cbs: 'Cannot be Stunned',
  ov_ycbstbbs: 'You cannot be slowed to below base speed',
  ov_garetys: 'Gain Accuracy Rating equal to your Strength',
  ov_iteawp: 'Immune to Elemental Ailments while Phasing',
  ov_caertadpnbter: 'Converts all Evasion Rating to Armour. Dexterity provides no bonus to Evasion Rating',
  ov_iteawocg: 'Immune to Elemental Ailments while on Consecrated Ground',
  ov_lriatesi: 'Life Regeneration is applied to Energy Shield instead',
  ov_ecllfy: 'Enemies Cannot Leech Life From You',
  ov_cbsiyhbhr: 'Cannot be Stunned if you haven\'t been Hit Recently',
  ov_eychm: 'Enemies you Curse have Malediction',
  ov_yccathe: 'Your Curses can apply to Hexproof Enemies',
  ov_iti: 'Immune to Ignite',
  ov_its: 'Immune to Shock',
  ov_neab: 'Nearby Enemies are Blinded',
  ov_cbb: 'Cannot be Blinded',
  ov_mscnm: 'Movement Skills cost no Mana',
  ov_ebcatu: 'Enemies Become Chilled as they Unfreeze',
  ov_lriboesiol: 'Light Radius is based on Energy Shield instead of Life',
  ov_lleanrafl: 'Life Leech effects are not removed at Full Life',
  ov_cs: 'Culling Strike',
  ov_htsehcs: 'Hits that Stun Enemies have Culling Strike',
  ov_kbeiygacswas: 'Knocks Back Enemies if you get a Critical Strike with a Staff',

  // Scion
  ascendant_templar: 'Can Allocate Passives from the Templar\'s starting point',
  ascendant_witch: 'Can Allocate Passives from the Witch\'s starting point',
  ascendant_shadow: 'Can Allocate Passives from the Shadow\'s starting point',
  ascendant_ranger: 'Can Allocate Passives from the Ranger\'s starting point',
  ascendant_marauder: 'Can Allocate Passives from the Marauder\'s starting point',
  ascendancy_duelist: 'Can Allocate Passives from the Duelist\'s starting point',

  // Shadow
  // trickster
  trickster_ea: '+# to maximum Energy Shield per # Evasion Rating on Body Armour',
  trickster_ea1: '+# to Evasion Rating per # Maximum Energy Shield on Helmet',
  trickster_ea2: 'Cannot be Stunned if you haven\'t been Hit Recently',
  trickster_ea3: '#% reduced Damage taken if you haven\'t been Hit Recently',
  trickster_pr: '#% increased Recovery Rate of Life, Mana and Energy Shield if you\'ve Killed an Enemy affected by your Damage Over Time Recently',
  trickster_pr1: 'Recover #% of Maximum Life on Kill',
  trickster_pr2: 'Recover #% of Maximum Energy Shield on Kill',
  trickster_pr3: 'Recover #% of Maximum Mana on Kill',

  // Templar
  // Guardian
  guardian_pog: 'Using Warcries is Instant',
  guardian_pog1: 'Warcries cost no Mana',

  // Hierophant
  hierophant_ab: 'Gain Arcane Surge when you or your Totems Hit an Enemy with a Spell',
  hierophant_ab1: 'Immune to Elemental Ailments while you have Arcane Surge',

  // Inquisitor
  inquisitor_aop: 'Nearby Enemies Take #% increased Elemental Damage',
  inquisitor_aop1: 'Nearby Enemies deal #% less Elemental Damage',
  inquisitor_iov: '#% increased Spell Damage if you\'ve Cast a Spell Recently',
  inquisitor_iov1: '#% increased Attack Damage if you\'ve Cast a Spell Recently',
  inquisitor_iov2: '#% increased Attack Speed if you\'ve Attacked Recently',
  inquisitor_iov3: '#% increased Cast Speed if you\'ve Attacked Recently',
  inquisitor_ij: 'Critical Strikes ignore Enemy Monster Elemental Resistances',
  inquisitor_ij1: 'Non-Critical Strikes Penetrate #% of Enemy Elemental Resistances',
  inquisitor_pp: '#% of maximum Mana and Energy Shield Regenerated per second while on Consecrated Ground',
  inquisitor_pp1: '#% increased Attack and Cast Speed while on Consecrated Ground',
  inquisitor_pp2: 'Immune to Elemental Ailments while on Consecrated Ground',

  // Duelist
  // Champion
  champion_f: 'You have Fortify',
  champion_wf: 'Enemies you Taunt take #% increased Damage',
  champion_wf1: 'Enemies Taunted by you cannot Evade Attacks',
  champion_i: 'You and nearby Allies deal #% increased Damage',
  champion_i1: 'You and nearby Allies have #% increased Movement Speed',
  champion_uh: '#% increased Attack Speed while you have Fortify',
  champion_uh1: '#% increased Melee Damage while you have Fortify',
  champion_uh2: '+# to Armour and Evasion Rating while you have Fortify',
  champion_uh3: 'Cannot be Stunned while you have Fortify',
  champion_ftsltf: 'Your Hits permanently Intimidate Enemies that are on Full Life',
  champion_ftsltf1: 'Gain Adrenaline for # seconds when you reach Low Life if you\ndo not have Adrenaline',
  champion_ftsltf2: 'Remove all Ailments and Burning when you gain Adrenaline',

  // Slayer
  slayer_h: '#% more Damage if you\'ve Killed Recently',
  slayer_h1: '#% increased Area of Effect if you\'ve Killed Recently',
  slayer_h2: 'Cannot take Reflected Physical Damage',
  slayer_eh: '#% of Overkill Damage is Leeched as Life',
  slayer_eh1: 'You are Immune to Bleeding while Leeching',
  slayer_bol: 'Gain Onslaught for # seconds when you Kill a Rare or Unique Enemy',
  slayer_bol2: 'Kill Enemies that have #% or lower Life when Hit by your Skills',
  slayer_o: 'Your Damaging Hits always Stun Enemies that are on Full Life',
  slayer_o1: '#% chance to double Stun Duration',


  // Marauder
  // Chieftain
  chieftain_rsl1: '#% of Life Regenerated per second if you\'ve taken Fire Damage from a Hit Recently',
  chieftain_rsl2: 'Unaffected by Ignite',
  chieftain_hdf: '#% of Fire Damage Leeched as Life',
  chieftain_hdf1: '#% chance to Cover Rare or Unique Enemies in Ash for # Seconds on Hit',
  chieftain_nfa: 'Every # seconds, gain #% of Physical Damage as Extra Fire Damage for # seconds',
  chieftain_twh: 'Totems are Immune to Fire Damage',
  chieftain_twh1: 'Totems have #% of your Armour',
  chieftain_twh2: 'Skills used by Totems have a #% chance to Taunt on Hit',
  chieftain_twh3: 'Totems Reflect #% of their maximum Life as Fire Damage to\nnearby Enemies when Hit',
  chieftain_tfs: '#% of maximum Life Regenerated per second per Endurance Charge',
  chieftain_tfs1: 'When you or your Totems Kill a Burning Enemy, #% chance for you\nand your Totems to each gain an Endurance Charge',
  chieftain_tfs2: '#% increased Fire Damage per Endurance Charge',

  // Berserker
  berserker_ror: 'Effects granted for having Rage are Doubled',
  berserker_ror1: 'Cannot be Stunned while you have at least # Rage',
  berserker_aoc: '#% more Damage',
  berserker_wb: 'Recover #% of Life and Mana when you use a Warcry',
  berserker_wb1: 'Gain # Rage when you use a Warcry',
  berserker_bf: '#% of Damage Leeched as Life if you\'ve taken a Savage Hit Recently',
  berserker_bf1: '#% increased Damage if you\'ve taken a Savage Hit Recently',
  berserker_bf2: '#% increased Attack Speed if you\'ve taken a Savage Hit Recently',

  // ascendancy specific
  as_MORE_p_pahdutmdttatsotmdldttatptf: 'Projectile Attack Hits deal up to #% more Damage to targets at the start of their movement, dealing less Damage to targets as the projectile travels farther',
  as_arid: 'Accuracy Rating is Doubled',
  as_tcscppaeut: '+#% to Critical Strike Chance per Poison affecting Enemy, up to +#%',
  as_ctiywgecyigutymnoec: '#% chance that if you would gain Endurance Charges, you instead gain up to your maximum number of Endurance Charges',
  as_yhpwamfc: 'You have Phasing while at maximum Frenzy Charges',
  as_yhpwyho: 'You have Phasing while you have Onslaught',
  as_mrpsiyuamsr: '# Mana Regenerated per second if you\'ve used a Movement Skill Recently',
  as_irrolmaesiykaeabydotr: '#% increased Recovery Rate of Life, Mana and Energy Shield if you\'ve Killed an Enemy affected by your Damage Over Time Recently',
  as_wykaefecotegoncdaecdfs: 'When you Kill an Enemy, for each Curse on that Enemy, gain #%\nof Non-Chaos Damage as extra Chaos Damage for # seconds',
  as_esrinibdirbr: 'Energy Shield Recharge is not interrupted by Damage if Recharge\nbegan Recently',
  as_pb: 'Cursed Enemies you or your Minions Kill have a #% chance to Explode, dealing a quarter of their maximum Life as Chaos Damage',
  as_nehrlrr: 'Nearby Enemies have #% reduced Life Regeneration rate',
  as_nehtcr: 'Nearby Enemies have -#% to Chaos Resistance',
  as_gapcaysatom: 'Gain a Power Charge after you Spend a total of # Mana',
  as_pdl: 'Gain #% increased Area of Effect for # seconds',
  as_pdl1: 'Gain #% increased Elemental Damage for # seconds',
  as_hr: '#% reduced Mana Reservation of Herald Skills',
  as_hr1: 'Damage penetrates #% Cold Resistance while affected by Herald of Ice',
  as_hr2: 'Damage penetrates #% Fire Resistance while affected by Herald of Ash',
  as_hr3: 'Damage penetrates #% Lightning Resistance while affected by Herald of Thunder',
  as_hr4: '#% increased Effect of Heralds on You',
  as_flux: 'Every # seconds:\nGain Chilling Conflux for # seconds\nGain Shocking Conflux for # seconds\nGain Igniting Conflux for # seconds\nGain Chilling, Shocking and Igniting Conflux for # seconds',
  as_gol: '#% increased Golem Damage for each Golem you have Summoned',
  as_gol1: 'You cannot be Chilled or Frozen while you have an Ice Golem Summoned',
  as_gol2: 'You cannot be Ignited while you have a Flame Golem Summoned',
  as_gol3: 'You cannot be Shocked while you have a Lightning Golem Summoned',
  as_gol4: 'Can Summon up to # additional Golem at a time',
  as_gol5: '#% increased Effect of Buffs granted by your Golems for each Summoned Golem',
  as_gol6: '#% increased Damage for each Summoned Golem',
  as_gol7: 'Your Elemental Golems are Immune to Elemental Damage',
  as_prolif: 'Elemental Ailments caused by your Skills spread to other nearby Enemies\nRadius: #',
  as_poc: 'For each Element you\'ve been hit by Damage of Recently, #% reduced Damage taken of that Element',
  as_poc1: 'For each Element you\'ve been hit by Damage of Recently, #% increased Damage of that Element',
  as_pyro: '#% reduced Mana Cost of Skills that place Mines or throw Trap',
  as_pyro1: '#% Life Regenerated per Second for each of your Traps Triggered Recently, up to #%',
  as_pyro2: '#% Life Regenerated per Second for each of your Mines Detonated Recently, up to #%',
  as_pc: '#% Chance for Traps to Trigger an additional time',
  as_pc1: 'You gain #% increased Damage for each Trap',
  as_ds: '#% chance when Placing Mines to Place an additional Mine',
  as_ds1: 'You gain #% increased Area of Effect for each Mine',
  as_ee: '#% reduced Damage taken from Traps and Mines',
  as_bs: '#% increased Damage if you Detonated Mines Recently',
  as_bs1: '#% increased Mine Laying Speed if you Detonated Mines Recently',
  as_cr: 'When your Traps Trigger, your nearby Traps also Trigger',
  as_cbs: 'Cannot be Stunned while you have at least # Rage',
  as_grwykae: 'Gain # Rage when you Kill an Enemy',
  as_cbswyhes: 'Cannot Be Stunned while you have Energy Shield',
  as_oesrpsfeeyoymhkrut: '#% of Energy Shield Regenerated per second for each\nEnemy You or your Minions have Killed Recently, up to #%',
  as_htv: 'Your Hits have #% chance to gain #% of Non-Chaos Damage as Extra Chaos Damage',
  as_i: 'Single-target Melee attacks deal Splash Damage to surrounding targets',
  as_aotc: 'You have Onslaught while on full Frenzy Charges',
  as_ctrommwyuas: '#% chance to Recover #% of Maximum Mana when you use a Skill',
  as_rf: 'Grants Armour equal to #% of your Reserved Life to you and nearby Allies',
  as_pog: 'Grants maximum Energy Shield equal to #% of your Reserved Mana to\nyou and nearby Allies',
  as_ton: 'Every # seconds, remove Curses and Elemental Ailments from you',
  as_ton1: 'Every # seconds, #% of Maximum Life Regenerated over one second',
  as_hop: 'Nearby Enemies cannot gain Power, Frenzy or Endurance Charges',
  as_bop: '#% additional Block Chance for # seconds every # seconds',
  as_bop1: 'If you\'ve Blocked in the past # seconds, you\nand nearby Allies cannot be Stunned',
  as_bop2: 'If you\'ve Attacked Recently, you\nand nearby Allies have #% chance to Block Attacks',
  as_bop3: 'If you\'ve Cast a Spell Recently, you\nand nearby Allies have #% chance to Block Spells',
  as_rdtfsasm: '#% reduced Damage Taken for # seconds after Spending # Mana',
  as_chutatsaat: 'Can have up to # additional Totem summoned at a time',

  // Keynodes
  k_mi: 'Minions explode when reduced to Low Life, dealing #% of their maximum Life as Fire Damage to surrounding Enemies',
  k_pcaldctfddnd: '#% of Physical, Cold and Lightning Damage Converted to Fire Damage\nDeal no Non-Fire Damage',
  k_mlbitcd: 'Maximum Life becomes #, Immune to Chaos Damage',
  k_cd: 'You can inflict Bleeding on an Enemy up to # times\nYour Bleeding does not deal extra Damage while the Enemy is moving\n#% less Damage with Bleeding',
  k_gr: 'Life Leech is applied to Energy Shield instead\n#% less Energy Shield Recharge Rate',
  k_vp: 'Life Leeched per Second is doubled.\nMaximum Life Leech Rate is doubled.\nLife Regeneration has no effect.',
  k_mom: 'Spend Energy Shield before Mana for Skill Costs\nEnergy Shield protects Mana instead of Life',
  k_ms: 'All bonuses from an Equipped Shield apply to your Minions instead of you',
  k_ab: 'You can\'t deal Damage with Skills yourself\nCan have up to # additional Totem summoned at a time',
  k_dw: '#% more chance to Evade Projectile Attacks\n#% less chance to Evade Melee Attacks',
  k_bm: 'Removes all mana. Spend Life instead of Mana for Skills',
};

module.exports = {
  scheme,
};
